### ISSUE TITLE
How translate Display Attribute ?

### ISSUE THREAD

**Issue by mtugnoli** [VPKSoft/Langlib#34]
Hi !

Is it possible to translate Display Attribute ?

es:

public class Class1
{
    [DisplayName("TranslateMe")]
    public virtual string Name { get; set; }
}

**Comment by VPKSoft** [comment]
Hi,
Currently this isn't possible. However this would make a good enhancement for the library as the library itself uses reflection to translate property values. I'll look into this once I have the time to do so 👍

This seems however to be more trickier than I thought; at least some articles suggest that an attribute cannot be changed via reflection, i.e. at [StackOverflow](https://stackoverflow.com/questions/10046601/change-custom-attributes-parameter-at-runtime). This is still worth to take a look into...

**Comment by VPKSoft** [comment]
Hi,
I'm sorry, but this can't be done.
I tried with the following code:
```C#
public class TestClass
{
    [DisplayName("TranslateMe")]
    public string Name { get; set; }
}

private void button1_Click(object sender, System.EventArgs e)
{
    var testClass = new TestClass();
    var attribute = (DisplayNameAttribute) testClass.GetType().GetProperty("Name")
        .GetCustomAttributes(typeof(DisplayNameAttribute), false)[0];

    var property = attribute.GetType().GetProperty("DisplayNameValue", BindingFlags.Instance | BindingFlags.NonPublic);
    property.SetValue(attribute, "TranslatedMe");


    attribute = (DisplayNameAttribute) testClass.GetType().GetProperty("Name")
        .GetCustomAttributes(typeof(DisplayNameAttribute), false)[0];
    var value = property.GetValue(attribute);
    MessageBox.Show(value.ToString());
```
And the result is still 'TranslateMe' as it should be 'TranslatedMe':
![image](https://user-images.githubusercontent.com/40712699/69399334-77d29900-0cf6-11ea-8e9a-c199658b2655.png)

Please re-open the issue if you have a working suggestion for this, I'm closing this for now.

**Comment by VPKSoft** [comment]
Hi,
I may have found a solution for you by sub-classing the [DisplayNameAttribute](docs.microsoft.com/en-us/dotnet/api/system.componentmodel.displaynameattribute) class.
This is the main form of the WinForms test application:
```cs
using System;
using System.ComponentModel;
using System.Windows.Forms;
using System.Reflection;
using VPKSoft.LangLib;

namespace LangLibTestWinforms
{
    public partial class FormMain : DBLangEngineWinforms
    {
        public FormMain()
        {
            InitializeComponent();
            if (DesignMode)
            {
                return;
            }

            DBLangEngine.DBName = "LangLibTestWinforms.sqlite";
            if (Utils.ShouldLocalize() != null)
            {
                DBLangEngine.InitializeLanguage("LangLibTestWinforms.Messages", Utils.ShouldLocalize(), false);
                return; // After localization don't do anything more.
            }


            DBLangEngine.InitializeLanguage("LangLibTestWinforms.Messages");
```

Now the sub-class code:
```cs
/// <summary>
/// A class to use LangLib for a <see cref="DisplayNameAttribute"/> translation.
/// Implements the <see cref="System.ComponentModel.DisplayNameAttribute" />
/// </summary>
/// <seealso cref="System.ComponentModel.DisplayNameAttribute" />
public class LangLibDisplayNameAttribute : DisplayNameAttribute
{
	private readonly string messageName;
	private readonly string defaultText;

	/// <summary>
	/// Initializes a new instance of the <see cref="LangLibDisplayNameAttribute"/> class.
	/// </summary>
	/// <param name="messageName">
	/// The text to look up for a translation from the message resource.
	/// This is also used as the default value for the <see cref="DisplayName"/> property.
	/// </param>
	public LangLibDisplayNameAttribute(string messageName)
	{
		this.messageName = messageName;
	}

	/// <summary>
	/// Initializes a new instance of the <see cref="LangLibDisplayNameAttribute"/> class.
	/// </summary>
	/// <param name="defaultText">The default text to use as a <see cref="DisplayName"/> property value.</param>
	/// <param name="messageName">The name of the translated text within the message resource.</param>
	public LangLibDisplayNameAttribute(string defaultText, string messageName)
	{
		this.messageName = messageName;
		this.defaultText = defaultText;
	}

	public override string DisplayName => // this might need a try / catch block..
		// assume the message name to be also the fallback localization..
		DBLangEngine.GetStatMessage(messageName, defaultText ?? messageName);
}
```

An the usage would be either this one (preferred):
```cs
[LangLibDisplayName("TranslateMe", "msgTranslateMe")]
public string TranslateMe { get; set; }
```
or just to use a single string as a text name and the default text (less preferred):
```cs
[LangLibDisplayName("TranslateMe")]
public string TranslateMe { get; set; }
```

This will need the text to be translated to be added to the message list resource file however:
![image](https://user-images.githubusercontent.com/40712699/69474873-15999700-0dcf-11ea-8f93-9c20694d0abd.png)

And then needs to be translated to which ever locale you wish using the tool within the library:
![image](https://user-images.githubusercontent.com/40712699/69474928-a4a6af00-0dcf-11ea-90c8-7c2e01851765.png)

Hope this helps 👍, and let me know if it did help 🙄
